___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [12]:
import numpy as np

#### Create an array of 10 zeros 

In [11]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [10]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [9]:
arr = np.arange(10)
arr[0:11] = 5

print(arr)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [14]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50

In [16]:
arr = np.arange(10,50,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [23]:
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [43]:
import numpy as np

ransom = np.random.rand(1)
print(ransom)

[0.21513263]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [45]:
ransom = np.random.randn(25)
print(ransom)

[-7.56644892e-01  4.16927031e-01  6.56673428e-01 -1.32220497e+00
  7.56429723e-02  1.28875524e+00  9.77471890e-01 -1.54957198e+00
  1.30120521e+00  7.08330578e-02  8.98889042e-01  2.87199867e-04
  1.32069058e+00 -1.71065387e+00 -1.22003490e+00 -3.22638276e-01
  1.68307255e-01 -5.39759065e-01  1.50727799e+00 -9.03792868e-01
 -1.59744132e+00 -6.12000642e-01 -6.08833614e-01  1.67307687e+00
  2.16213316e-01]


#### Create the following matrix:

In [49]:
x = np.arange(0,1,0.01).reshape(10,10)
print(x)

[[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
 [0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19]
 [0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29]
 [0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39]
 [0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]
 [0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89]
 [0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [52]:
x = np.linspace(0,1,20)
print(x)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [56]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
x = np.arange(1,26).reshape(5,5)
x[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [83]:
x[3:4,4]

array([20])

20

In [77]:
x = np.arange(1,26).reshape(5,5)
x[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [80]:
x[4:]

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [81]:
x[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [85]:
print(x.sum())

325


#### Get the standard deviation of the values in mat

In [86]:
print(x.std())

7.211102550927978


#### Get the sum of all the columns in mat

In [87]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!